yatube/about/urls.py
from django.urls import path

from .views import AboutAuthorView, TechTemplateView

app_name = 'about'


urlpatterns = [
    path('about_author/', AboutAuthorView.as_view(), name='about_author'),
    path('tech/', TechTemplateView.as_view(), name='tech')
]

yatube/posts/urls.py
from django.urls import path
from posts.views import (IndexListView, PostCreateView, PostDeleteView,
                         PostDetailView, PostListView, PostUpdateView,
                         ProfileListView, PostSearchView)

app_name = 'posts'


urlpatterns = [
    path('', IndexListView.as_view(), name='index'),
    path('group_posts/<slug:slug>', PostListView.as_view(), name='group_posts'),
    path('post_create/', PostCreateView.as_view(), name='post_create'),
    path('post_detail/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('post_update/<int:pk>/', PostUpdateView.as_view(), name='post_update'),
    path('profile/<int:pk>', ProfileListView.as_view(), name='profile'),
    path('post_delete/<int:pk>', PostDeleteView.as_view(), name='post_delete'),
    path('posts_search/', PostSearchView.as_view(), name='posts_search'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
]

yatube/templates/includes/footer.html
{% load static %}

<p>© {% now "Y" %} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
{% load static %}

<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube
    </a>

    <!--<form class="form-inline my-2 my-lg-0" action="{% url 'posts:posts_search' %}">
      <input class="form-inline" type="search" placeholder="Искать здесь..." aria-label="Search" name="search">
      <button class="btn btn-primary" type="submit">Поиск</button>
    </form>-->

      <ul class="nav nav-pills">

        {% with request.resolver_match.view_name as view_name %}

        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'about:about_author' %}
          active{% endif %}" href="{% url 'about:about_author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %}
          active{% endif %}" href="{% url 'about:tech' %}">Технологии</a>
        </li>

        {% endwith %}

      {% if user.is_authenticated %}
        {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item">
        <a class="nav-link {% if view_name  == 'posts:post_create' %}
           active{% endif %}" href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        {% endwith %}

        {% if user.last_name %}
        {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'users:password_change_form' %}
          active{% endif %}" href="{% url 'users:password_change_form' user.id %}">Сменить пароль</a>
        </li>
        {% endwith %}
        {% endif %}

        {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'users:logout' %}
          active{% endif %}" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        {% endwith %}

      {% else %}
        {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'users:login' %}
          active{% endif %}" href="{% url 'users:login' %}">Войти</a>
        {% endwith %}

        </li>
        {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item">
           <a class="nav-link {% if view_name  == 'users:registration' %}
          active{% endif %}" href="{% url 'users:registration' %}">Регистрация</a>
        </li>
        {% endwith %}

      {% endif %}
      
      <form class="form-inline" action="{% url 'posts:posts_search' %}">
        <input class="form-control" type="text" placeholder="Поиск..." aria-label="Search" name="search">
      </form>

    </ul>
  </div>
</nav>