yatube/about/urls.py
from django.urls import path

from .views import AboutAuthorView, TechTemplateView

app_name = 'about'


urlpatterns = [
    path('about_author/', AboutAuthorView.as_view(), name='about_author'),
    path('tech/', TechTemplateView.as_view(), name='tech')
]

yatube/posts/urls.py
from django.urls import path
from posts.views import (IndexListView, PostCreateView, PostDeleteView,
                         PostDetailView, PostListView, PostUpdateView,
                         ProfileListView, PostSearchView)

app_name = 'posts'


urlpatterns = [
    path('', IndexListView.as_view(), name='index'),
    path('group_posts/<slug:slug>', PostListView.as_view(), name='group_posts'),
    path('post_create/', PostCreateView.as_view(), name='post_create'),
    path('post_detail/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('post_update/<int:pk>/', PostUpdateView.as_view(), name='post_update'),
    path('profile/<int:pk>', ProfileListView.as_view(), name='profile'),
    path('post_delete/<int:pk>', PostDeleteView.as_view(), name='post_delete'),
    path('posts_search/', PostSearchView.as_view(), name='posts_search'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
]

yatube/posts/models.py
from django.db import models
from users.models import User


class Group(models.Model):
    title = models.CharField(max_length=150)
    slug = models.SlugField(unique=True)
    description = models.CharField(max_length=254)

    def __str__(self):
        return f'{self.title}'


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )

    class Meta:
        ordering = ['-pub_date']

yatube/posts/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = {
            'text': 'Текст',
            'group': 'Группа'
        }

yatube/posts/views.py
from typing import Any, Dict
from django.db.models.query import QuerySet
from common.views import TitleMixin
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.db.models import Q

from .forms import PostForm
from .models import Group, Post


class IndexListView(TitleMixin, ListView):
    paginate_by = 5
    model = Post
    template_name = 'posts/index.html'
    title = 'Последние обновления'

    
class PostListView(ListView):
    paginate_by = 5
    model = Post
    template_name = 'posts/group_list.html'

    def get_queryset(self):
        queryset = super(PostListView, self).get_queryset()
        slug = self.kwargs.get('slug')
        group = Group.objects.get(slug=slug)
        group_id = group.id
        return queryset.filter(group=group_id)

    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        context['group'] = Group.objects.get(slug=self.kwargs.get('slug'))
        slug = self.kwargs.get('slug')
        context['title'] = f'Посты группы {slug}'
        return context
    

class PostSearchView(ListView):
    paginate_by = 5
    model = Post
    template_name = 'posts/group_list.html'

    def get_queryset(self):
        queryset = super(PostSearchView, self).get_queryset()
        search_query = self.request.GET.get('search', '')       
        if search_query:
            try:
                group_id = Group.objects.get(title=search_query).id
            except(TypeError, ValueError, OverflowError, Group.DoesNotExist):
                group_id = None
            if group_id == None:
                return queryset.filter(text__icontains=search_query)
            else:
                return queryset.filter(Q(text__icontains=search_query) | Q(group=group_id))
        else:
            return queryset
    
    def get_context_data(self):
        search_query = self.request.GET.get('search', '')
        context = super(PostSearchView, self).get_context_data()
        context['title'] = f'Результаты поиска по запросу "{search_query}"'
        return context

    

class ProfileListView(ListView):
    paginate_by = 5
    model = Post
    template_name = 'posts/profile.html'

    def get_queryset(self):
        queryset = super(ProfileListView, self).get_queryset()
        user = self.kwargs.get('pk')
        return queryset.filter(author=user)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Посты автора {self.request.user}'
        context['len'] = len(Post.objects.filter(author=self.kwargs.get('pk')))
        return context
    

class PostCreateView(TitleMixin, CreateView):    
    model = Post
    fields = ('text', 'group')
    template_name = 'posts/post_create.html'
    success_url = reverse_lazy('posts:index')
    title = 'Новый пост'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super(PostCreateView, self).form_valid(form)
    

class PostDetailView(TitleMixin, DetailView):
    model = Post
    template_name = 'posts/post_detail.html'
    title = 'Детали поста'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['len'] = len(Post.objects.filter(author=self.object.author))
        return context
    

class PostUpdateView(TitleMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/post_update.html'
    title = 'Изменение поста'
    
    def get_success_url(self):
        return reverse_lazy('posts:post_detail', args=(self.kwargs.get('pk'),))
    

class PostDeleteView(DeleteView):
    model = Post
    template_name = 'posts/post_delete.html'
    success_url = reverse_lazy('posts:index')

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
  <div class="container py-5">
    <h1>{{ title }}</h1>
    <p>
      {{ group.description }}
    </p>    
    <article>
      {% for post in object_list %}
        <hr>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:'d M Y' }}
          </li>
        </ul>      
      <p>
      {{ post.text|truncatewords:30 }}
    </p>
    <a href="{% url 'posts:post_detail' post.id %}">детали поста</a>        
    </article>    
        {% endfor %}

  {% if page_obj.has_other_pages %}
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lt;</a>
          </li>
        {% endif %}
        {% for p in paginator.page_range %}
          {% if page_obj.number == p %}
            <li class="page-link">
              <a class="page-link" href="?page={{ p }}">{{ p }}</a>
            </li>
          {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}  
            <li class="page-item">
              <a class="page-link" href="?page={{ p }}">{{ p }}</a>
            </li>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&gt;</a>
          </li>
        {% endif %}
      </ul>
    </nuv>
  {% endif %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="container py-5">     
    <h1>Последние обновления на сайте</h1>
    
    <article>
    {% for post in object_list %}
      <hr>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:'d M Y' }}
        </li>
      </ul>      
      <p>
        {{ post.text|truncatewords:30 }}
      </p>
      {% if post.group %}
      <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a><br>
      {% endif %}
      <a href="{% url 'posts:post_detail' post.id %}">детали поста</a>
    </article>
    {% endfor %}
    
    

  {% if page_obj.has_other_pages %}
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lt;</a>
          </li>
        {% endif %}
        {% for p in paginator.page_range %}
          {% if page_obj.number == p %}
            <li class="page-link">
              <a class="page-link" href="?page={{ p }}">{{ p }}</a>
            </li>
          {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}  
            <li class="page-item">
              <a class="page-link" href="?page={{ p }}">{{ p }}</a>
            </li>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&gt;</a>
          </li>
        {% endif %}
      </ul>
    </nuv>
    {% endif %}
  </div>
{% endblock %}

yatube/templates/posts/post_create.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            Новый пост             
          </div>
          <div class="card-body">        
            <form method="post" action="{% url 'posts:post_create' %}">
              {% csrf_token %}           
              <div class="form-group row my-3 p-3">
                <label for="id_text">
                  Текст поста                  
                  <span class="required text-danger" >*</span>                  
                </label>
                {% for object in form %}
                  {{ object.text }}
                {% endfor %}
                <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">
                </textarea>                
                <small id="id_text-help" class="form-text text-muted">
                  Текст нового поста
                </small>                  
              </div>            
              <div class="form-group row my-3 p-3">
                <label for="id_group">
                  Группа                  
                </label>
                <select name="group" class="form-control" id="id_group">
                  {% for object in form.group %}
                  <option value="{{ object.id }}">{{ object }}</option>
                  {% endfor %}
                </select>
                <small id="id_group-help" class="form-text text-muted">
                  Группа, к которой будет относиться пост
                </small>
              </div>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  Сохранить
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/post_delete.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            
          </div>
          <div class="card-body">
           <form method="post">
            {% csrf_token %}
             <p>Вы действительно хотите удалить пост "{{ object.text|truncatewords:30 }}"?</p>
             {{ form }}
             <input class="btn btn-primary" type="submit" value="Удалить">
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ object.pub_date|date:'d M Y' }}
          </li>
          {% if object.group %}              
          <li class="list-group-item">
            Группа: {{ object.group.title }}<br>
            <a href="{% url 'posts:group_posts' object.group.slug %}">
              все записи группы
            </a>
          </li>
          {% endif %}            
          <li class="list-group-item">
            Автор: {{ object.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span >{{ len }}</span>
          </li>
          {% if len > 1 %}
          <li class="list-group-item">
            <a href="{% url 'posts:profile' object.author.id %}">
              все посты пользователя
            </a>
          </li>
          {% endif %}
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        <p>
          {{ object.text|truncatewords:30 }}
        </p>
        {% if user == object.author %}
        <a class="btn btn-primary" href="{% url 'posts:post_update' object.id %}">
          редактировать запись
        </a><br><br>
        <a class="btn btn-primary" href="{% url 'posts:post_delete' object.id %}">
          удалить запись
        </a>
        {% endif %}               
      </article>
    </div>     
  </div>
{% endblock %}

yatube/templates/posts/post_update.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            Редактировать пост             
          </div>
          <div class="card-body">        
            <form method="post" action="{% url 'posts:post_update' object.id %}">
              {% csrf_token %}            
              <div class="form-group row my-3 p-3">
                <label for="form.text_id_for_label">
                  Текст поста                  
                  <span class="required text-danger" >*</span>                  
                </label>
                <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">{{ object.text }}
                </textarea>                
                <small id="id_text-help" class="form-text text-muted">
                  Текст нового поста
                </small>                  
              </div>            
              <div class="form-group row my-3 p-3">
                <label for="id_group">
                  Группа                  
                </label>
                <select name="group" class="form-control" id="id_group">
                  {% for obj in form.group %}  
                  <option value="{{ obj.id }}" selected>{{ obj }}</option>
                  {% endfor %}
                </select>
                <small id="id_group-help" class="form-text text-muted">
                  Группа, к которой будет относиться пост
                </small>
              </div>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  Добавить
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="container py-5">        
  <h1>Все посты пользователя {{ object_list.first.author.get_full_name }} </h1>
  <h3>Всего постов: {{ len }} </h3> 
  {% for post in object_list %}
    <hr>
      <article>
        <ul>
          <li>
            Дата публикации: {{ post.pub_date|date:'d M Y' }} 
          </li>
        </ul>
        <p>
          {{ post.text|truncatewords:30 }} 
        </p>
      <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
    </article>
    {% if post.group %}       
      <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
    {% endif %}
  {% endfor %}
        
  {% if page_obj.has_other_pages %}
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lt;</a>
          </li>
        {% endif %}
        {% for p in paginator.page_range %}
          {% if page_obj.number == p %}
            <li class="page-link">
              <a class="page-link" href="?page={{ p }}">{{ p }}</a>
            </li>
          {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}  
            <li class="page-item">
              <a class="page-link" href="?page={{ p }}">{{ p }}</a>
            </li>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&gt;</a>
          </li>
        {% endif %}
      </ul>
    </nuv>
  {% endif %}
</div>
{% endblock %}