yatube/about/urls.py
from django.urls import path

from .views import AboutAuthorView, TechTemplateView

app_name = 'about'


urlpatterns = [
    path('about_author/', AboutAuthorView.as_view(), name='about_author'),
    path('tech/', TechTemplateView.as_view(), name='tech')
]

yatube/users/urls.py
from django.urls import path

from .views import (EmailConfirm, PasswordChangeDone, PasswordChangeFormView,
                    PasswordResetComplete, PasswordResetConfView,
                    PasswordResetDoneView, PasswordResetFormView,
                    UserLoginView, UserRegistrationview, logoutview)

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('registration/', UserRegistrationview.as_view(), name='registration'),
    path('logout/', logoutview, name='logout'),
    path('email_confirm/<str:uidb64>/<str:token>/', EmailConfirm.as_view(), name='email_confirm'),
    path('password_reset_form/', PasswordResetFormView.as_view(), name='password_reset_form'),
    path('password_change_form/<int:pk>', PasswordChangeFormView.as_view(), name='password_change_form'),
    path('password_change_done/', PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<str:uidb64>/<str:token>/', 
         PasswordResetConfView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', PasswordResetComplete.as_view(), name='password_reset_complete'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
]

yatube/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):

    email = models.EmailField(unique=True, blank=True, null=True)

yatube/users/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.forms import (AuthenticationForm, PasswordChangeForm,
                                       PasswordResetForm, SetPasswordForm,
                                       UserCreationForm)
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode

from .models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите имя пользователя'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите пароль'
    }))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите имя'
    }))    
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите фамилию'
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите имя пользователя'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите адрес электронной почты'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите пароль'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Подтвердите пароль'
    }))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')
    
    
class EmailForm(PasswordResetForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите адрес эл.почты'
    }))    
    
    class Meta:
        model = User
        fields = ('email',)

    def send_email(self, *args, **kwargs):
        try:
            user = User.objects.get(email=self.cleaned_data['email'])
            token = default_token_generator.make_token(user)
            uidb64 = urlsafe_base64_encode(force_bytes(user.pk))
            link = reverse_lazy('users:password_reset_confirm', kwargs={'uidb64': uidb64, 'token': token})
            link_ver = f'Перейдите по ссылке {settings.DOMAIN_NAME}{link}'
        except:
            user = None
            token = 'not_active_token'
            uidb64 = 'user_none'
            link = reverse_lazy('users:password_reset_confirm', kwargs={'uidb64': uidb64, 'token': token})
            link_ver = f'Для изменения пароля перейдите по ссылке {settings.DOMAIN_NAME}{link}'
        send_mail(
            subject='Изменение пароля',
            message=link_ver,
            from_email=kwargs.get('from_email'),
            recipient_list=[self.cleaned_data['email']],
            fail_silently=False,
        )

    def save(self, *args, **kwargs):        
        apts = {
        'from_email': kwargs.get('from_email'),
        }
        self.send_email(**apts)

        
class PasswordSetForm(SetPasswordForm):
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите новый пароль'
    }))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control'
    }))

    class Meta:
        model=User
        fields = ('new_password1', 'new_password2')
    


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите старый пароль'
    }))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите новый пароль'
    }))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Повторите новый пароль'
    }))

    class Meta:       
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')

yatube/users/views.py
#from datetime import datetime as dt
#from typing import Any, Dict

from common.views import TitleMixin
from django.conf import settings
from django.contrib.auth import logout
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import (LoginView, PasswordChangeView,
                                       PasswordResetConfirmView,
                                       PasswordResetView)
#from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.views.generic.base import TemplateView, View
from django.views.generic.edit import CreateView

from .forms import (EmailForm, PasswordSetForm, UserLoginForm,
                    UserPasswordChangeForm, UserRegistrationForm)
from .models import User


class UserRegistrationview(TitleMixin, CreateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'users/registration.html'
    success_url = reverse_lazy('users:login')
    title = 'Регистрация'

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()        
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        domain_name = settings.DOMAIN_NAME
        token = default_token_generator.make_token(user)
        link = reverse_lazy('users:email_confirm', kwargs={'uidb64': uid, 'token': token})
        link_ver = f'{domain_name}{link}'        
        send_mail(
            subject='Подтвердите свой электронный адрес',
            message=f'Перейдите по ссылке: {link_ver}, чтобы подтвердить регистрацию',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email],
            fail_silently=False,
        )
        
        title = 'Письмо активации отправлено'
        return render(self.request, 'users/email_confirmation_sent.html', context={'title': title})
    

class EmailConfirm(View):
    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64)
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            title = 'Поздравляем, Вы активированы!'
            return render(request, 'users/email_confirmed.html', context={'title': title})            
        else:
            title = 'Ваша электронная почта не активирована'
            return render(request, 'users/email_confirmation.html', context={'title': title})


class UserLoginView(TitleMixin, LoginView):
    form_class = UserLoginForm
    template_name = 'users/login.html'
    title = 'Авторизация'

    def get_success_url(self):
        return reverse_lazy('posts:index')


def logoutview(request):
    logout(request)
    return redirect('users:login')


class PasswordChangeFormView(PasswordChangeView):
    form_class = UserPasswordChangeForm
    template_name = 'users/password_change_form.html'
    success_url = reverse_lazy('users:password_change_done')

    def get_context_data(self, **kwargs):
        context = super(PasswordChangeFormView, self).get_context_data(**kwargs)
        context['us'] = self.request.user
        context['title'] = f'Изменение пароля для пользователя: {self.request.user.username}'
        return context


class PasswordChangeDone(TemplateView):
    template_name = 'users/password_change_done.html'


class PasswordResetFormView(TitleMixin ,PasswordResetView):
    form_class = EmailForm
    template_name = 'users/password_reset_form.html'
    success_url = reverse_lazy('users:password_reset_done')
    from_email = settings.EMAIL_HOST_USER
    title = 'Восстановление пароля'


class PasswordResetDoneView(TemplateView):    
    template_name = 'users/password_reset_done.html'


class PasswordResetConfView(TitleMixin ,PasswordResetConfirmView):
    form_class = PasswordSetForm
    template_name = 'users/password_reset_confirm.html'
    success_url = reverse_lazy('users:password_reset_complete')

    def get_context_data(self, **kwargs):
        context = super(PasswordResetConfView, self).get_context_data(**kwargs)
        context['uidb64'] = self.kwargs.get('uidb64')
        context['token'] = self.kwargs.get('token')
        context['user'] = self.user
        context['title'] = f'Восстановление пароля для пользователя: {self.user}'
        return context


class PasswordResetComplete(TemplateView):
    template_name = 'users/password_reset_complete.html'

yatube/templates/users/email_confirmation.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">         
      <div class="card-body" align="center">
        <p><font size="5">{{ title }}</font></p>
        </div> 
      </div>
    </div>
  </div>
</div>  
{% endblock %}

yatube/templates/users/email_confirmation_sent.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">          
      </div>
        <div class="card-body" align="center">
          <p><font size="5">{{ title }}</font></p>
        </div>        
          <p>
            На ваш адрес электронной почты было отправлено письмо с подтверждением. Пожалуйста, проверьте свою электронную почту и нажмите на ссылку подтверждения, чтобы завершить регистрацию.
            Если письмо не пришло, проверьте папку спам.
          </p>
        </div>
      </div>
     </div>
    </div>
  </div>  
{% endblock %}

yatube/templates/users/email_confirmed.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">         
      <div class="card-body" align="center">
        <p><font size="5">{{ title }}</font></p>
      </div>      
    </div>
  </div>
</div>  
{% endblock %}

yatube/templates/users/login.html
{% extends 'base.html' %}

{% load static %}

{% load socialaccount %}

{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          <form method="post" action="{% url 'users:login' %}">
            {% csrf_token %}        
            <div class="form-group row my-3">
              {{ form.username.errors }}
              <label for="{{ form.username.id_for_label }}">
                Имя пользователя
                <span class="required text-danger">*</span>
              </label>
                {{ form.username }}
            </div>
            <div class="form-group row my-3">
              {{ form.password.errors }}
              <label for="{{ form.password.id_for_label}}">
                Пароль
                <span class="required text-danger">*</span>
              </label>
              {{ form.password }}
            </div>
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Войти
              </button>
              <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
                Забыли пароль?
              </a>
            </div>
          </form>
        </div> 
      </div>
    <br>    
    <div class="container py-2 d-inline-block">      
      <div class="offset-md-4">
        <p>Войти с помощью:  
    <a class="navbar-brand justify-content-center" href="{% provider_login_url 'github' %}">
      <img src="{% static 'img/Github.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">                 
      <span style="color:black">Git</span>hub
    </a> </p>     
    <!--<a class="navbar-brand justify-content-center" href="{% provider_login_url 'facebook' %}">
      <img src="{% static 'img/facebook.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">                 
      <span style="color:black">Face</span>book
    </a>-->
      </div>
    </div>
  </div>



  </div>
</div>
</div>

{% endblock %}

yatube/templates/users/password_change_done.html
{% extends 'base.html' %}


{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Пароль изменён
        </div>
        <div class="card-body"> 
          <p>Пароль изменён успешно</p>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
</div>
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Изменить пароль
        </div>
        <div class="card-body">
          <form method="post" action="{% url 'users:password_change_form' us.id %}">
            {% csrf_token %}
            <div class="form-group row my-3 p-3">
              {{ form.old_password.errors }}
              <label for="{{ form.old_password.id_for_label }}">
                Старый пароль
                <span class="required text-danger">*</span>
              </label>    
              {{ form.old_password }}
            </div>
            <div class="form-group row my-3 p-3">
              {{ form.new_password1.errors }}
              <label for="{{ form.new_password1.id_for_label }}">
                Новый пароль
                <span class="required text-danger">*</span>
              </label>    
              {{ form.new_password1 }}
                <small id="id_new_password1-help" class="form-text text-muted">
                  <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                </small>
            </div>
            <div class="form-group row my-3 p-3">
              {{ form.new_password2.errors }}
              <label for="{{ form.new_password2.id_for_label }}">
                Подтверждение нового пароля
                <span class="required text-danger">*</span>
              </label>    
              {{ form.new_password2 }}
            </div>
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Изменить пароль
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/password_confirm.html
{% extends 'base.html' %}

{% block content %}     
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Отправлено письмо
        </div>
        <div class="card-body">
          <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
        </div> 
      </div> 
    </div>
  </div> 
</div>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Восстановление пароля завершено
        </div>
        <div class="card-body">
          <p>Ваш пароль был сохранен. Используйте его для входа</p>
          <a href="{% url 'users:login' %}">войти</a>
        </div> 
      </div> 
    </div>
  </div> 
</div>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends 'base.html' %}


{% block content %}
<div class="container py-5">
  {% if user %} 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Введите новый пароль
        </div>
        <div class="card-body">
          <form method="post" action="{% url 'users:password_reset_confirm' uidb64 token %}">
            {% csrf_token %}
            <div class="form-group row my-3 p-3">
              {{ form.new_password1.errors }}
              <label for="{{ form.new_password1.id_for_label }}">
                Новый пароль        
                <span class="required text-danger">*</span>        
              </label>    
              {{ form.new_password1 }}      
              <small id="id_new_password1-help" class="form-text text-muted">
                <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
              </small>      
            </div>
            <div class="form-group row my-3 p-3">
              {{ form.new_password2.errors }}
              <label for="{{ form.new_password2.id_for_label }}">
                Подтверждение нового пароля        
                <span class="required text-danger">*</span>        
              </label>    
              {{ form.new_password2 }}      
            </div>
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Назначить новый пароль
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  {% else %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Ошибка
        </div>
        <div class="card-body">
          <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
</div>
{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends 'base.html' %}

{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header"></div>
          Отправлено письмо
        </div>
        <div class="card-body">
          <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
        </div> 
      </div> 
    </div>
  </div> 
</div>
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
        </div>
        <div class="card-body"> 
          <form method="post" action="{% url 'users:password_reset_form' %}">
            {% csrf_token %}
            <div class="form-group row my-3 p-3">
              
              <label for="{{ form.email.id_for_label }}">
                Адрес электронной почты
                <span class="required text-danger">*</span>
              </label>    
              {{ form.email }}
            </div>
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Сбросить пароль
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>  
</div>
{% endblock %}

yatube/templates/users/password_reset_form_none.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">         
      <div class="card-body" align="center">
        <p><font size="5">Проверьте правильность электронной почты</font></p>
      </div>
    </div>
  </div>
 </div>
</div>  
{% endblock %}

yatube/templates/users/registration.html
{% extends 'base.html' %}

{% load static %}


{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Зарегистрироваться
          </div>
          <div class="card-body">
            <form method="post" action="{% url 'users:registration' %}">
              {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="{{ form.first_name.id_for_label }}">Имя</label>    
                {{ form.first_name }}     
              </div>
              <div class="form-group row my-3 p-3">
                <label for="{{ form.last_name.id_for_label }}">Фамилия</label>    
                {{ form.last_name }}
              </div>
              <div class="form-group row my-3 p-3">
                <label for="{{ form.username.id_for_label }}">
                  Имя пользователя
                  <span class="required text-danger">*</span>
                </label>    
                {{ form.username }}
                  <small id="id_username-help" class="form-text text-muted">
                    Обязательное поле. Не более 150 символов. Только буквы, цифры и символы @/./+/-/_.
                  </small>
              </div>
                <div class="form-group row my-3 p-3">
                  <label for="{{ form.email.id_for_label }}">Адрес электронной почты</label>    
                  {{ form.email }}     
                </div>
              <div class="form-group row my-3 p-3">
                <label for="{{ form.password1.id_for_label }}">
                  Пароль        
                  <span class="required text-danger">*</span>
                </label>    
                {{ form.password1}}
                <small id="id_password1-help" class="form-text text-muted">
                  <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="{{ form.password2.id_for_label }}">
                  Подтверждение пароля
                  <span class="required text-danger">*</span>
                </label>    
                {{ form.password2 }}
                <small id="id_password2-help" class="form-text text-muted">
                  Для подтверждения введите, пожалуйста, пароль ещё раз.
                </small>
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>

              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}